openapi: "3.0.0"
info:
  version: 1.0.0
  title: API for Testing Additional Schema Properties
paths:
  /test:
    get:
      responses:
        '200':
          description: A sample response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    readOnly: true
                  name:
                    type: string
                    maxLength: 50
                    minLength: 1
                  items:
                    type: array
                    minItems: 1
                    uniqueItems: true
                    contains:
                      type: string
                  properties:
                    type: object
                    maxProperties: 10
                    minProperties: 1
                    dependencies:
                      name: ["id"]
                  media:
                    type: string
                    format: binary
                  discriminator:
                    propertyName: "name"
                required:
                  - id
                  - name
                if:
                  properties:
                    name:
                      const: "test"
                then:
                  properties:
                    id:
                      minimum: 1
                      exclusiveMinimum: true
                else:
                  properties:
                    id:
                      minimum: 0
                      exclusiveMinimum: false
