openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Simple API"
paths:
  /endpoint:
    get:
      parameters:
        - name: "param1"
          in: "query"
          required: true
          schema:
            type: "string"
        - name: "param2"
          in: "query"
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestBody"
      responses:
        '200':
          description: "Successful response"
          headers:
            X-My-Header:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
components:
  schemas:
    RequestBody:
      type: "object"
      properties:
        field1:
          type: "string"
    Response:
      type: "object"
      properties:
        field1:
          type: "string"
